name: Lint and Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # --- İŞ 1: Kod Kalitesini Kontrol Et ---
  lint:
    name: Run Linter Checks
    runs-on: ubuntu-latest # Bu iş için GitHub'ın kendi sanal makinesini kullanabiliriz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0' # LTS versiyonu

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

  # --- İŞ 2: Sunucuya Dağıt ---
  deploy:
    name: Deploy to VPS
    needs: lint # Bu işin başlaması için 'lint' işinin başarılı olmasını bekle
    runs-on: self-hosted # Bu işi bizim sunucumuzdaki runner çalıştıracak

    steps:
      - name: Pull latest source code
        run: git pull origin main
        working-directory: /home/ibra/projects/fokus-web-app

      - name: Rebuild and Deploy Docker Container
        run: |
          docker compose down
          docker compose up -d
        working-directory: /home/ibra/projects/fokus-web-app
